### PR TITLE
Add RHEL 7 as a test image

### PR DESCRIPTION
**Pull request by danragnar**
RHEL 7 test image from the RHEL7 universal base image.

### CODE REVIEW

**Review by tadeboro — APPROVED** [review]
Great work, @danragnar. I have no comments about the code. But there is one thing that is bothering me a bit: are we allowed to redistribute the derivate of `ubi7/ubi` using hub.docker.com? I did read some docs about them and got the feeling that this is something we are allowed to do. But I would sleep better if I were to know for sure. Do you have any information regarding this?

**Comment by danragnar** [comment]
@tadeboro According to this: https://developers.redhat.com/articles/ubi-faq/#redistribution it is allowed. It seems a bit ambiguous if you can package your own software on top and redistribute (point 20 & 22), but in this case we're only redistributing stuff in the UBI repo's.

**Comment by tadeboro** [comment]
Thanks for looking into the redistribution part. I think it should be safe to upload this to the hub.docker.com and if not, we can still remove those images.

I have just one more thing to ask. Can we use `ubi7/ubi-init` as a base instead? This way, we can use this same exact image for other tests that require a running init system.

**Comment by danragnar** [comment]
Done!

**Pull request merged**
